name: Continous integration

on:
  pull_request:
  push:
    branches:
      - main
      
env:
  ENVIRONMENT: dev
      
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Run tests'
        run: sh ./run-tests.sh
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: 'report.xml'
      - name: 'Upload Test Results'
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            cucumber.json
            report.xml
          retention-days: 5
